version 1
setup:
  - apt-get update
  - |
      apt-get install -y xvfb libgtk-3-0 libnss3 libgbm-dev libdrm2 libasound2 libatk-bridge2.0-0 gconf-service libxshmfence1 curl unzip
      if ! apt-get install -y terraform; then
        curl -Lo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
        unzip -o /tmp/terraform.zip -d /usr/local/bin
      fi
  - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
  - apt-get install -y nodejs
  - cd frontend && npm ci && npx cypress install && cd ..
  - pip install -r backend/requirements.txt
test:
  - python -m pytest -q
  - cd frontend && xvfb-run -a npx cypress run --browser electron --headless && cd ..
  - cd infra/terraform && terraform fmt -check && terraform init -backend=false && terraform plan -input=false -lock=false -var-file=../live/variables.tfvars && cd ../..
env:
  CYPRESS_CACHE_FOLDER: .cache/Cypress
