version: 1
setup:
  - apt-get update
  - apt-get install -y gnupg software-properties-common curl
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  - apt-get update
  - |
      apt-get install -y xvfb libgtk-3-0 libnss3 libgbm-dev libdrm2 libasound2 libatk-bridge2.0-0 gconf-service libxshmfence1 curl unzip
      if ! terraform --version 2>/dev/null | grep -q "1.4.6"; then
        curl -Lo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
        unzip -o /tmp/terraform.zip -d /usr/local/bin
        chmod +x /usr/local/bin/terraform
      fi
  - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
  - apt-get install -y nodejs
  - cd frontend && npm ci && npx cypress install && cd ..
  - pip install -r backend/requirements.txt
test:
  - python -m pytest -q
  - cd frontend && xvfb-run -a npx cypress run --browser electron --headless && cd ..
  - cd frontend && npm run build
  - cd infra/terraform && terraform fmt -check && bash ci-plan.sh && cd ../..
env:
  CYPRESS_CACHE_FOLDER: .cache/Cypress
  TF_IN_AUTOMATION: "1"
