version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001
      - FLASK_APP=backend.server
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app/backend/static
  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_API_URL=http://web:5001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
