services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001
      - FLASK_APP=backend.server
      - GAME_FILE=/app/runtime/game_persist.json
      - LOBBIES_FILE=/app/runtime/lobbies.json
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app/backend/static
      - ./data:/app/data:ro
      - ./runtime:/app/runtime
  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    environment:
      - VITE_API_URL=http://web:5001
    depends_on:
      - web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    profiles:
      - dev
